# Generated by Django 3.0.5 on 2023-11-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0003_auto_20231120_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='job_profile',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='student',
        ),
        migrations.DeleteModel(
            name='JobProfile',
        ),
        migrations.DeleteModel(
            name='StudentApplication',
        ),
    ]
