# Generated by Django 3.0.5 on 2023-11-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_userdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
    ]
