# Generated by Django 3.0.5 on 2023-11-03 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20231103_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='DOB',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Roll_no',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
