# Generated by Django 3.0.5 on 2023-11-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20231103_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
