# Generated by Django 3.0.5 on 2023-11-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20231103_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='DOB',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Roll_no',
            field=models.IntegerField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
