# Generated by Django 3.0.5 on 2023-11-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20231103_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Roll_no',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
