# Generated by Django 3.0.5 on 2023-11-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20231103_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='DOB',
            field=models.DateField(default=None),
        ),
    ]
