# Generated by Django 3.0.5 on 2023-11-04 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20231103_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(null=True, upload_to='student_images/'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='rollno',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
