# Generated by Django 3.0.5 on 2023-11-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20231104_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='GPA',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
