# Generated by Django 3.0.5 on 2023-11-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20231105_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='department',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student_Id',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
