# Generated by Django 3.0.5 on 2023-11-21 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college_management', '0004_auto_20231121_1602'),
        ('student', '0018_auto_20231106_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('resume', models.FileField(upload_to='uploads/')),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('placement_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_management.PlacementDrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
